FROM python:3-alpine

MAINTAINER zhengquan.hu "zhengquan.hu@qq.com"

RUN pip install requests pika MySQL-python

WORKDIR /app

#CMD ["supervisord", "--nodaemon", "-c", "/data/daemonize/supervisord.conf"] 
